import { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { z } from 'zod';
import { Globe, TrendingUp, BarChart3, Loader2, Copy, CheckCircle2, ArrowRight, UserPlus, Share2, DollarSign } from 'lucide-react';
import { motion } from 'framer-motion';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/features/auth/AuthProvider';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { REFERRAL_COUNTRIES, REFERRAL_LANGUAGES } from '@/features/referral/lib/constants';

const signupSchema = z.object({
  full_name: z.string().trim().min(2, 'Please enter your full name').max(100),
  email: z.string().trim().email('Invalid email address').max(255),
  password: z.string().min(8, 'Password must be at least 8 characters').max(72),
  country: z.string().min(1, 'Please select a country'),
  language_preference: z.string().min(1, 'Please select a language'),
  agency_name: z.string().trim().max(120).optional().or(z.literal('')),
  phone: z.string().trim().max(40).optional().or(z.literal('')),
  wechat_id: z.string().trim().max(60).optional().or(z.literal('')),
});

export default function ReferralLandingPage() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [submitting, setSubmitting] = useState(false);
  const [success, setSuccess] = useState<{ code: string; needsVerification: boolean } | null>(null);
  const [form, setForm] = useState({
    full_name: '',
    email: '',
    password: '',
    country: '',
    language_preference: 'zh',
    agency_name: '',
    phone: '',
    wechat_id: '',
  });

  const update = (k: keyof typeof form, v: string) => setForm(s => ({ ...s, [k]: v }));

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const parsed = signupSchema.safeParse(form);
    if (!parsed.success) {
      toast.error(parsed.error.errors[0].message);
      return;
    }
    setSubmitting(true);
    try {
      // 1) Sign up the user (email verification required)
      const { data: authData, error: authError } = await supabase.auth.signUp({
        email: parsed.data.email,
        password: parsed.data.password,
        options: {
          emailRedirectTo: `${window.location.origin}/referral/dashboard`,
          data: { full_name: parsed.data.full_name, role_intent: 'referral_agent' },
        },
      });
      if (authError) throw authError;
      if (!authData.user) throw new Error('Signup failed');

      // 2) Insert referral_agents row (referral_code is auto-generated by DB trigger)
      const { data: agentRow, error: insertError } = await supabase
        .from('referral_agents')
        .insert({
          user_id: authData.user.id,
          full_name: parsed.data.full_name,
          email: parsed.data.email,
          country: parsed.data.country,
          language_preference: parsed.data.language_preference,
          agency_name: parsed.data.agency_name || null,
          phone: parsed.data.phone || null,
          wechat_id: parsed.data.wechat_id || null,
          referral_code: '', // trigger will overwrite
        } as any)
        .select('referral_code')
        .maybeSingle();

      if (insertError) throw insertError;
      if (!agentRow?.referral_code) throw new Error('Could not generate referral code');

      setSuccess({
        code: agentRow.referral_code,
        needsVerification: !authData.session,
      });
    } catch (err: any) {
      console.error('[ReferralSignup]', err);
      toast.error(err.message || 'Signup failed');
    } finally {
      setSubmitting(false);
    }
  };

  if (success) {
    const referralLink = `${window.location.origin}/buy?ref=${success.code}`;
    const copy = (text: string, label: string) => {
      navigator.clipboard.writeText(text);
      toast.success(`${label} copied`);
    };
    return (
      <>
        <Helmet><title>Welcome to ListHQ Referral Network</title></Helmet>
        <div className="min-h-screen bg-background flex items-center justify-center px-4 py-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-lg w-full bg-card border border-border rounded-2xl shadow-elevated p-8 text-center"
          >
            <div className="w-14 h-14 rounded-full bg-emerald-500/10 flex items-center justify-center mx-auto mb-4">
              <CheckCircle2 className="text-emerald-600" size={28} />
            </div>
            <h1 className="font-display text-2xl font-bold text-foreground">You're in!</h1>
            <p className="text-muted-foreground mt-2 text-sm">
              {success.needsVerification
                ? 'Check your email to verify your account, then log in to access your dashboard.'
                : 'Your referral account is active. Start sharing your link to earn commissions.'}
            </p>

            <div className="mt-6 p-5 rounded-xl bg-secondary/50 border border-border">
              <p className="text-xs uppercase tracking-wider text-muted-foreground font-medium">Your referral code</p>
              <p className="font-display text-4xl font-bold text-primary tracking-widest mt-2">{success.code}</p>
              <Button variant="ghost" size="sm" onClick={() => copy(success.code, 'Code')} className="mt-2 gap-1.5">
                <Copy size={14} /> Copy code
              </Button>
            </div>

            <div className="mt-4 p-4 rounded-xl bg-primary/5 border border-primary/20 text-left">
              <p className="text-xs text-muted-foreground mb-1">Your referral link</p>
              <p className="text-sm font-mono break-all text-foreground">{referralLink}</p>
              <Button variant="outline" size="sm" onClick={() => copy(referralLink, 'Link')} className="mt-3 gap-1.5">
                <Copy size={14} /> Copy link
              </Button>
            </div>

            <div className="mt-6 flex flex-col gap-2">
              <Button onClick={() => navigate('/referral/dashboard')} className="gap-2">
                Go to dashboard <ArrowRight size={16} />
              </Button>
              <Link to="/" className="text-sm text-muted-foreground hover:text-foreground">Back to home</Link>
            </div>
          </motion.div>
        </div>
      </>
    );
  }

  return (
    <>
      <Helmet>
        <title>Referral Program | ListHQ</title>
        <meta name="description" content="Refer a property buyer or seller and earn with ListHQ's referral network." />
      </Helmet>
      <div className="min-h-screen bg-background">
        {/* Hero */}
        <section className="bg-gradient-to-br from-primary/5 via-background to-cyan-accent/5 border-b border-border">
          <div className="max-w-5xl mx-auto px-4 py-14 md:py-20 text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-xs font-semibold mb-6">
              <Globe size={14} /> International Agent Network
            </div>
            <h1 className="font-display text-3xl md:text-5xl font-bold text-foreground tracking-tight">
              Join the ListHQ International Referral Network
            </h1>
            <p className="text-base md:text-lg text-muted-foreground mt-4 max-w-2xl mx-auto">
              Earn commissions connecting global buyers with Australian property
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-10 max-w-3xl mx-auto">
              <div className="bg-card border border-border rounded-xl p-5">
                <Globe className="text-primary mb-2" size={22} />
                <p className="font-display text-2xl font-bold text-foreground">15+</p>
                <p className="text-sm text-muted-foreground">Countries</p>
              </div>
              <div className="bg-card border border-border rounded-xl p-5">
                <TrendingUp className="text-primary mb-2" size={22} />
                <p className="font-display text-2xl font-bold text-foreground">A$500–$2,000</p>
                <p className="text-sm text-muted-foreground">Per settled referral</p>
              </div>
              <div className="bg-card border border-border rounded-xl p-5">
                <BarChart3 className="text-primary mb-2" size={22} />
                <p className="font-display text-2xl font-bold text-foreground">Real-time</p>
                <p className="text-sm text-muted-foreground">Tracking dashboard</p>
              </div>
            </div>
          </div>
        </section>

        {/* How it works */}
        <section className="max-w-5xl mx-auto px-4 pt-12">
          <div className="text-center mb-8">
            <h2 className="font-display text-2xl md:text-3xl font-bold text-foreground">How it works</h2>
            <p className="text-sm text-muted-foreground mt-2">Get started in three simple steps</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {[
              { icon: UserPlus, step: 1, text: 'Sign up & get your unique referral code' },
              { icon: Share2, step: 2, text: 'Share your code with buyers interested in Australian property' },
              { icon: DollarSign, step: 3, text: 'Earn AUD $500–$2,000 for every settled purchase' },
            ].map(({ icon: Icon, step, text }) => (
              <div key={step} className="bg-card border border-border rounded-2xl p-6 text-center shadow-card">
                <div className="w-12 h-12 mx-auto rounded-full bg-primary/10 flex items-center justify-center text-primary mb-3">
                  <Icon size={22} />
                </div>
                <p className="text-xs uppercase tracking-wider font-semibold text-primary mb-1">Step {step}</p>
                <p className="text-sm text-foreground">{text}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Form */}
        <section className="max-w-2xl mx-auto px-4 py-12">
          <div className="bg-card border border-border rounded-2xl shadow-card p-6 md:p-8">
            <h2 className="font-display text-2xl font-bold text-foreground">Create your referral account</h2>
            <p className="text-sm text-muted-foreground mt-1">Get your unique referral code and start earning today.</p>

            {user && (
              <div className="mt-4 p-3 rounded-lg bg-amber-50 border border-amber-200 text-sm text-amber-900 dark:bg-amber-900/20 dark:text-amber-200 dark:border-amber-700">
                You're already signed in. If you've already registered as a referral agent, <Link to="/referral/dashboard" className="underline font-medium">go to your dashboard</Link>.
              </div>
            )}

            <form onSubmit={handleSubmit} className="mt-6 space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="full_name">Full name *</Label>
                  <Input id="full_name" value={form.full_name} onChange={e => update('full_name', e.target.value)} required maxLength={100} />
                </div>
                <div>
                  <Label htmlFor="email">Email *</Label>
                  <Input id="email" type="email" value={form.email} onChange={e => update('email', e.target.value)} required maxLength={255} />
                </div>
              </div>

              <div>
                <Label htmlFor="password">Password *</Label>
                <Input id="password" type="password" value={form.password} onChange={e => update('password', e.target.value)} required minLength={8} maxLength={72} />
                <p className="text-xs text-muted-foreground mt-1">At least 8 characters.</p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="country">Country *</Label>
                  <select
                    id="country"
                    value={form.country}
                    onChange={e => update('country', e.target.value)}
                    required
                    className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                  >
                    <option value="">Select country</option>
                    {REFERRAL_COUNTRIES.map(c => <option key={c} value={c}>{c}</option>)}
                  </select>
                </div>
                <div>
                  <Label htmlFor="language_preference">Preferred language *</Label>
                  <select
                    id="language_preference"
                    value={form.language_preference}
                    onChange={e => update('language_preference', e.target.value)}
                    required
                    className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                  >
                    {REFERRAL_LANGUAGES.map(l => <option key={l.code} value={l.code}>{l.label}</option>)}
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="agency_name">Agency / Company name</Label>
                  <Input id="agency_name" value={form.agency_name} onChange={e => update('agency_name', e.target.value)} maxLength={120} />
                </div>
                <div>
                  <Label htmlFor="phone">Phone</Label>
                  <Input id="phone" type="tel" value={form.phone} onChange={e => update('phone', e.target.value)} maxLength={40} />
                </div>
              </div>

              <div>
                <Label htmlFor="wechat_id">WeChat ID</Label>
                <Input id="wechat_id" value={form.wechat_id} onChange={e => update('wechat_id', e.target.value)} maxLength={60} />
              </div>

              <Button type="submit" disabled={submitting} className="w-full gap-2">
                {submitting && <Loader2 size={16} className="animate-spin" />}
                {submitting ? 'Creating account…' : 'Create referral account'}
              </Button>

              <p className="text-xs text-muted-foreground text-center">
                By signing up you agree to our <Link to="/terms" className="underline">Terms</Link> and <Link to="/privacy" className="underline">Privacy Policy</Link>.
              </p>
            </form>
          </div>
        </section>
      </div>
    </>
  );
}
