import { createClient } from 'npm:@supabase/supabase-js@2';
import { getCorsHeaders } from '../_shared/cors.ts';

// Generates a CSV trust audit report for a state + date range.
// (CSV is acceptable for accountant import; PDF generation can layer on later.)
Deno.serve(async (req) => {
  const corsHeaders = getCorsHeaders(req.headers.get('Origin'));
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  const json = (body: unknown, status = 200) =>
    new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) return json({ error: 'Unauthorized' }, 401);
    const token = authHeader.replace('Bearer ', '').trim();

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
    );

    const { data: userData } = await supabase.auth.getUser(token);
    const caller = userData?.user;
    if (!caller) return json({ error: 'Unauthorized' }, 401);

    const { data: roleCheck } = await supabase
      .from('user_roles').select('role').eq('user_id', caller.id).eq('role', 'admin').maybeSingle();
    if (!roleCheck) return json({ error: 'Forbidden' }, 403);

    const body = await req.json().catch(() => ({}));
    const state = String(body.state || 'NSW').toUpperCase();
    const from = String(body.from || '');
    const to = String(body.to || '');
    if (!from || !to) return json({ error: 'from and to dates required (YYYY-MM-DD)' }, 400);

    let query = supabase
      .from('trust_account_transactions')
      .select('id, occurred_at, type, amount_cents, reference, party_name, agent_id, property_id, state, reconciled_at')
      .gte('occurred_at', `${from}T00:00:00Z`)
      .lte('occurred_at', `${to}T23:59:59Z`)
      .order('occurred_at', { ascending: true });
    if (state !== 'ALL') query = query.eq('state', state);

    const { data: txs, error } = await query;
    if (error) return json({ error: `Query failed: ${error.message}` }, 500);

    const rows = txs || [];
    const headers = ['id', 'occurred_at', 'type', 'amount_aud', 'reference', 'party_name', 'agent_id', 'property_id', 'state', 'reconciled_at'];
    const escape = (v: unknown) => {
      if (v == null) return '';
      const s = String(v);
      return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
    };
    const csv = [
      `# ListHQ Trust Account Audit Report`,
      `# State: ${state}`,
      `# Period: ${from} to ${to}`,
      `# Generated: ${new Date().toISOString()}`,
      `# Generated by: ${caller.email || caller.id}`,
      `# Row count: ${rows.length}`,
      headers.join(','),
      ...rows.map((r) => headers.map((h) => {
        if (h === 'amount_aud') return escape(((r.amount_cents ?? 0) / 100).toFixed(2));
        return escape((r as Record<string, unknown>)[h]);
      }).join(',')),
    ].join('\n');

    return new Response(csv, {
      status: 200,
      headers: {
        ...corsHeaders,
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="trust-audit-${state}-${from}-to-${to}.csv"`,
      },
    });
  } catch (e) {
    console.error('[export-trust-audit-report] error', e);
    return json({ error: (e as Error).message || 'Internal error' }, 500);
  }
});
