// Generate a PDF for an owner statement and store it in Supabase Storage.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const AUD = (n: number) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD', minimumFractionDigits: 2 }).format(Number(n) || 0);
const FMT = (d: string | null) => d ? new Date(d).toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, serviceKey);

    // ── AUTH: require valid JWT ──
    const token = req.headers.get("Authorization")?.replace("Bearer ", "") ?? "";
    const { data: { user }, error: authError } = await supabase.auth.getUser(token);
    if (authError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const { statement_id } = await req.json();
    if (!statement_id) {
      return new Response(JSON.stringify({ error: 'statement_id required' }), { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    const { data: stmt, error } = await supabase
      .from('owner_statements')
      .select('*, properties(address, suburb, owner_name)')
      .eq('id', statement_id)
      .maybeSingle();

    if (error || !stmt) {
      return new Response(JSON.stringify({ error: 'Statement not found' }), { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    // ── OWNERSHIP: caller must be the statement's agent OR an admin ──
    const { data: callerAgent } = await supabase
      .from('agents')
      .select('id')
      .eq('user_id', user.id)
      .maybeSingle();
    const { data: adminRole } = await supabase
      .from('user_roles')
      .select('role')
      .eq('user_id', user.id)
      .eq('role', 'admin')
      .maybeSingle();

    const isOwner = callerAgent?.id && callerAgent.id === (stmt as any).agent_id;
    const isAdmin = !!adminRole;
    if (!isOwner && !isAdmin) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), {
        status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const property = (stmt as any).properties || {};
    const otherDeductions: Array<{ label: string; amount: number }> = (stmt.other_deductions_breakdown as any) || [];
    const otherRows = otherDeductions.map(d =>
      `<tr><td>${escapeHtml(d.label || 'Other')}</td><td align="right">−${AUD(Number(d.amount))}</td></tr>`
    ).join('');

    const notesHtml = stmt.statement_notes
      ? `<p style="margin-top:24px;padding:12px;background:#f9f9f9;border-left:3px solid #1a2e4a;font-size:13px"><strong>Notes:</strong> ${escapeHtml(stmt.statement_notes)}</p>`
      : '';

    const html = `<html><body style="font-family:Arial,sans-serif;max-width:700px;margin:40px auto;color:#1a1a1a">
<h1 style="font-size:20px;border-bottom:2px solid #1a2e4a;padding-bottom:8px">Owner Statement</h1>
<p><strong>Property:</strong> ${escapeHtml(property.address || '—')}</p>
<p><strong>Owner:</strong> ${escapeHtml(property.owner_name || '—')}</p>
<p><strong>Period:</strong> ${FMT(stmt.period_start)} – ${FMT(stmt.period_end)}</p>
<table width="100%" cellpadding="8" style="border-collapse:collapse;margin-top:20px">
<tr style="background:#f5f5f5"><td>Gross rent collected</td><td align="right">${AUD(stmt.gross_rent_aud)}</td></tr>
<tr><td>Management fee</td><td align="right">−${AUD(stmt.management_fee_aud)}</td></tr>
<tr><td>Maintenance costs</td><td align="right">−${AUD(stmt.maintenance_costs_aud)}</td></tr>
${otherRows}
<tr style="border-top:2px solid #1a2e4a;font-weight:bold"><td>Net amount to owner</td><td align="right">${AUD(stmt.net_amount_aud)}</td></tr>
</table>
${notesHtml}
<p style="margin-top:40px;font-size:11px;color:#888">Generated by ListHQ · AFA 2014 compliant · ${new Date().toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' })}</p>
</body></html>`;

    // Convert HTML to PDF via free html2pdf.app endpoint
    const pdfRes = await fetch('https://html2pdf.app/f', {
      method: 'POST',
      headers: { 'Content-Type': 'text/html' },
      body: html,
    });

    if (!pdfRes.ok) {
      const text = await pdfRes.text().catch(() => '');
      console.error('html2pdf.app failed', pdfRes.status, text.slice(0, 200));
      return new Response(JSON.stringify({ error: 'PDF generation failed', detail: text.slice(0, 200) }), {
        status: 502, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const pdfBytes = new Uint8Array(await pdfRes.arrayBuffer());
    const path = `${stmt.agent_id}/${stmt.id}.pdf`;

    const { error: upErr } = await supabase.storage
      .from('owner-statements')
      .upload(path, pdfBytes, { contentType: 'application/pdf', upsert: true });

    if (upErr) {
      console.error('Storage upload failed', upErr);
      return new Response(JSON.stringify({ error: 'Upload failed', detail: upErr.message }), {
        status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const { data: pub } = supabase.storage.from('owner-statements').getPublicUrl(path);
    const pdf_url = pub.publicUrl;

    await supabase.from('owner_statements').update({ pdf_url }).eq('id', statement_id);

    return new Response(JSON.stringify({ pdf_url }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (err) {
    console.error(err);
    return new Response(JSON.stringify({ error: (err as Error).message }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});

function escapeHtml(s: string): string {
  return String(s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
}
