/**
 * Shared print-ready HTML invoice template used by:
 *  - BrokerPortal (broker invoices the agent for the referral fee)
 *  - BrokerReferralsPage (agent-side copy of the same invoice)
 */
export interface InvoiceData {
  invoiceNumber: string;
  fromName: string;
  fromEmail: string;
  toName: string;
  toRef: string;
  buyerName: string;
  loanAmount: string;
  amount: string;
}

export function buildInvoiceHtml(d: InvoiceData): string {
  const date = new Date().toLocaleDateString("en-AU", {
    day: "numeric", month: "long", year: "numeric",
  });
  const esc = (s: string) =>
    String(s).replace(/[&<>"']/g, (c) => (
      { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string
    ));

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Tax Invoice ${esc(d.invoiceNumber)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #0f172a; max-width: 760px; margin: 40px auto; padding: 0 32px; }
  h1 { font-size: 32px; letter-spacing: 2px; margin: 0 0 4px; }
  .muted { color: #64748b; font-size: 13px; }
  .row { display: flex; justify-content: space-between; gap: 24px; margin-top: 32px; }
  .block { flex: 1; }
  .label { text-transform: uppercase; font-size: 11px; letter-spacing: 1px; color: #64748b; margin-bottom: 6px; }
  .value { font-size: 14px; line-height: 1.5; }
  table { width: 100%; border-collapse: collapse; margin-top: 32px; }
  th, td { text-align: left; padding: 12px 8px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
  th { background: #f8fafc; text-transform: uppercase; font-size: 11px; letter-spacing: 1px; color: #475569; }
  .total { font-size: 22px; font-weight: 700; text-align: right; margin-top: 16px; }
  .terms { margin-top: 32px; padding: 16px; background: #f8fafc; border-radius: 8px; font-size: 13px; color: #475569; }
  footer { margin-top: 48px; text-align: center; color: #94a3b8; font-size: 12px; border-top: 1px solid #e2e8f0; padding-top: 16px; }
  .actions { margin: 24px 0; text-align: right; }
  button { background: #2563eb; color: white; border: 0; padding: 10px 18px; border-radius: 6px; font-size: 14px; cursor: pointer; }
  @media print { .actions { display: none; } body { margin: 0; } }
</style>
</head>
<body>
  <div class="actions"><button onclick="window.print()">Print / Save as PDF</button></div>
  <h1>TAX INVOICE</h1>
  <p class="muted">Invoice ${esc(d.invoiceNumber)} · ${esc(date)}</p>

  <div class="row">
    <div class="block">
      <div class="label">From</div>
      <div class="value">
        <strong>${esc(d.fromName)}</strong><br/>
        ${esc(d.fromEmail)}
      </div>
    </div>
    <div class="block">
      <div class="label">To</div>
      <div class="value">
        <strong>${esc(d.toName)}</strong><br/>
        Ref: ${esc(d.toRef)}
      </div>
    </div>
  </div>

  <table>
    <thead>
      <tr><th>Description</th><th style="text-align:right">Amount</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>Mortgage referral fee — ${esc(d.buyerName)}, loan est. ${esc(d.loanAmount)}</td>
        <td style="text-align:right">${esc(d.amount)}</td>
      </tr>
    </tbody>
  </table>
  <div class="total">Total: ${esc(d.amount)} <span class="muted" style="font-size:12px;font-weight:400">(inc. GST if applicable)</span></div>

  <div class="terms">
    <strong>Payment terms:</strong> Payment due within 7 business days of settlement.
  </div>

  <footer>Generated by ListHQ — referral platform</footer>
</body>
</html>`;
}
