import { supabase } from '@/integrations/supabase/client';

const UNSPLASH = [
  '1600596542815-ffad4c1539a9',
  '1568605114967-8130f3a36994',
  '1583608205776-bfd35f0d9f83',
  '1512917774080-9991f1c4c750',
  '1600585154340-be6161a56a0c',
  '1564013799919-ab600027ffc6',
  '1570129477492-45c003edd2be',
  '1613490493576-4aa9328fba5e',
  '1502672260266-1c1ef2d93688',
  '1600047509807-ba8f99d2cdde',
  '1560185007-cde436f6a4d0',
  '1523217582562-09d05ab4be96',
];

const img = (i: number) => `https://images.unsplash.com/photo-${UNSPLASH[i % UNSPLASH.length]}?w=800&q=80`;

const recentDate = (daysAgo: number) => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString().slice(0, 10);
};

const v = () => Math.floor(Math.random() * 321) + 80;

export async function seedProperties() {
  const { data: agent, error: agentErr } = await supabase.from('agents').select('id').limit(1).single();
  if (agentErr || !agent) throw new Error('No agent found — create an agent first.');
  const aid = agent.id;

  const props = [
    // ── Sydney ──
    { title:'House in Mosman NSW', address:'14 Avenue Rd, Mosman NSW 2088', suburb:'Mosman', state:'NSW', price:3850000, price_formatted:'$3,850,000', listing_type:'sale', beds:4, baths:3, parking:2, sqm:620, property_type:'House', year_built:1935, description:'Elegant family home set on a north-facing block with panoramic harbour views. Meticulously renovated with a heritage facade and contemporary interiors. Short stroll to Balmoral Beach and elite schools.', features:['Pool','Harbour views','Double garage','Ducted AC','Home theatre','Alfresco','Wine cellar'], slug:'house-mosman-nsw-a1b2c3d4', img_i:0, days:3 },
    { title:'Apartment in Bondi Beach NSW', address:'22/180 Campbell Pde, Bondi Beach NSW 2026', suburb:'Bondi Beach', state:'NSW', price:1650000, price_formatted:'$1,650,000', listing_type:'sale', beds:2, baths:1, parking:1, sqm:95, property_type:'Apartment', year_built:2005, description:'Sun-drenched beachside apartment with sweeping ocean views from the living area and master bedroom. Open-plan living with stone kitchen and engineered timber floors. Walk to cafes, surf clubs and transport.', features:['Ocean views','Balcony','Intercom','Lift access','Built-in robes'], slug:'apartment-bondi-beach-nsw-b2c3d4e5', img_i:1, days:5 },
    { title:'Terrace in Paddington NSW', address:'48 Glenmore Rd, Paddington NSW 2021', suburb:'Paddington', state:'NSW', price:2200000, price_formatted:'$2,200,000', listing_type:'sale', beds:3, baths:2, parking:0, sqm:155, property_type:'House', year_built:1890, description:'Beautifully restored Victorian terrace with original lacework, fireplaces and tessellated tile hallway. Rear extension opens to a private courtyard with established gardens. Moments to Oxford Street galleries and boutiques.', features:['Courtyard','Fireplace','Restored heritage','Skylights','Gas cooking'], slug:'terrace-paddington-nsw-c3d4e5f6', img_i:2, days:7 },
    { title:'House in Manly NSW', address:'6 Bower Ln, Manly NSW 2095', suburb:'Manly', state:'NSW', price:4200000, price_formatted:'$4,200,000', listing_type:'sale', beds:5, baths:3, parking:2, sqm:480, property_type:'House', year_built:2018, description:'Architecturally designed coastal residence just 300 metres from Manly Beach. Five generous bedrooms across three levels with a rooftop terrace capturing ocean breezes. Entertainer\'s kitchen with integrated Miele appliances.', features:['Rooftop terrace','Pool','Solar panels','Ducted AC','Triple garage','Smart home'], slug:'house-manly-nsw-d4e5f6g7', img_i:3, days:2 },
    { title:'Apartment in Newtown NSW', address:'8/92 King St, Newtown NSW 2042', suburb:'Newtown', state:'NSW', price:820000, price_formatted:'$820,000', listing_type:'sale', beds:2, baths:1, parking:0, sqm:72, property_type:'Apartment', year_built:2010, description:'Stylish inner-west apartment in the heart of Newtown\'s vibrant dining and arts precinct. North-facing living with polished concrete floors and stone benchtops. Pet-friendly strata with rooftop garden.', features:['Rooftop garden','Pet-friendly','Polished concrete','Built-in robes','Intercom'], slug:'apartment-newtown-nsw-e5f6g7h8', img_i:4, days:12 },
    { title:'House in Balmain NSW', address:'31 Darling St, Balmain NSW 2041', suburb:'Balmain', state:'NSW', price:2800000, price_formatted:'$2,800,000', listing_type:'sale', beds:4, baths:2, parking:1, sqm:310, property_type:'House', year_built:1910, description:'Charming sandstone-fronted Federation home on one of Balmain\'s most coveted streets. Original fireplaces and stained glass complement a sleek rear addition. Private garden and studio ideal for home office.', features:['Garden','Studio','Fireplace','Sandstone facade','Skylight','Gas cooking'], slug:'house-balmain-nsw-f6g7h8i9', img_i:5, days:8 },
    { title:'Apartment in Pyrmont NSW', address:'15/22 Bowman St, Pyrmont NSW 2009', suburb:'Pyrmont', state:'NSW', price:1180000, price_formatted:'$1,180,000', listing_type:'sale', beds:2, baths:2, parking:1, sqm:110, property_type:'Apartment', year_built:1998, description:'Converted warehouse apartment with soaring 4-metre ceilings, exposed brick and original timber columns. Open-plan living flows to a generous entertainer\'s balcony. Walking distance to Darling Harbour and the CBD.', features:['Warehouse conversion','High ceilings','Exposed brick','Balcony','Security parking'], slug:'apartment-pyrmont-nsw-g7h8i9j0', img_i:6, days:14 },
    { title:'House in Coogee NSW', address:'5 Brook St, Coogee NSW 2034', suburb:'Coogee', state:'NSW', price:3650000, price_formatted:'$3,650,000', listing_type:'sale', beds:5, baths:3, parking:2, sqm:550, property_type:'House', year_built:1940, description:'Substantial Art Deco family home perched above Coogee Beach with uninterrupted ocean panorama. Heated pool, level lawn and cabana for year-round entertaining. Recently upgraded kitchen with Calacatta marble island.', features:['Ocean views','Heated pool','Cabana','Double garage','Ducted AC','Marble kitchen','Solar panels'], slug:'house-coogee-nsw-h8i9j0k1', img_i:7, days:4 },
    { title:'Apartment in Surry Hills NSW', address:'3/12 Crown St, Surry Hills NSW 2010', suburb:'Surry Hills', state:'NSW', price:650, price_formatted:'$650/wk', listing_type:'rent', beds:1, baths:1, parking:0, sqm:52, property_type:'Apartment', year_built:2015, description:'Sleek one-bedroom apartment in a boutique Surry Hills block with rooftop terrace access. Integrated kitchen with gas cooking and stone benchtops. Steps to Central Station and Crown Street dining.', features:['Rooftop terrace','Gas cooking','Intercom','Built-in robe','Air conditioning'], slug:'apartment-surry-hills-nsw-i9j0k1l2', img_i:8, days:6 },

    // ── Melbourne ──
    { title:'House in Toorak VIC', address:'28 St Georges Rd, Toorak VIC 3142', suburb:'Toorak', state:'VIC', price:6500000, price_formatted:'$6,500,000', listing_type:'sale', beds:5, baths:4, parking:3, sqm:920, property_type:'House', year_built:1925, description:'Grand period residence behind established hedges on one of Toorak\'s premier streets. Five opulent bedrooms, formal lounge with marble fireplace and a championship-size tennis court. Pool, triple garage and self-contained guest quarters.', features:['Tennis court','Pool','Guest quarters','Marble fireplace','Triple garage','Wine cellar','Alarm system'], slug:'house-toorak-vic-j0k1l2m3', img_i:9, days:1 },
    { title:'Apartment in South Yarra VIC', address:'1204/33 Park St, South Yarra VIC 3141', suburb:'South Yarra', state:'VIC', price:1250000, price_formatted:'$1,250,000', listing_type:'sale', beds:2, baths:2, parking:1, sqm:88, property_type:'Apartment', year_built:2019, description:'Contemporary high-rise apartment with floor-to-ceiling glass capturing city and parkland vistas. European kitchen, stone bathroom and engineered oak flooring throughout. Residents enjoy pool, gym and concierge.', features:['City views','Pool','Gym','Concierge','Video intercom','Storage cage'], slug:'apartment-south-yarra-vic-k1l2m3n4', img_i:10, days:9 },
    { title:'Townhouse in Richmond VIC', address:'12A Church St, Richmond VIC 3121', suburb:'Richmond', state:'VIC', price:1100000, price_formatted:'$1,100,000', listing_type:'sale', beds:3, baths:2, parking:1, sqm:140, property_type:'Townhouse', year_built:2016, description:'Modern three-bedroom townhouse on the fringe of Bridge Road shopping. Split-level design with north-facing courtyard and rooftop terrace perfect for sunset entertaining. Walk to MCG and Richmond station.', features:['Rooftop terrace','Courtyard','Split-level','Alarm','Dishwasher'], slug:'townhouse-richmond-vic-l2m3n4o5', img_i:11, days:11 },
    { title:'Victorian in Fitzroy VIC', address:'76 Gertrude St, Fitzroy VIC 3065', suburb:'Fitzroy', state:'VIC', price:1850000, price_formatted:'$1,850,000', listing_type:'sale', beds:3, baths:2, parking:0, sqm:175, property_type:'House', year_built:1880, description:'Classic double-fronted Victorian with ornate ceilings, deep verandah and original Baltic pine floors. Rear warehouse-style extension floods the living zone with natural light. Moments to Brunswick Street cafes and galleries.', features:['Heritage facade','Ornate ceilings','Skylight','Courtyard','Gas fireplace'], slug:'victorian-fitzroy-vic-m3n4o5p6', img_i:0, days:15 },
    { title:'Art Deco Apartment in St Kilda VIC', address:'4/62 Fitzroy St, St Kilda VIC 3182', suburb:'St Kilda', state:'VIC', price:750000, price_formatted:'$750,000', listing_type:'sale', beds:2, baths:1, parking:1, sqm:78, property_type:'Apartment', year_built:1938, description:'Beautifully preserved Art Deco apartment with leadlight windows, picture rails and high decorative ceilings. North-facing balcony looks over Fitzroy Street towards Port Phillip Bay. Walk to Luna Park and Acland Street.', features:['Art Deco features','Balcony','Leadlight windows','High ceilings','OFP'], slug:'apartment-st-kilda-vic-n4o5p6q7', img_i:1, days:18 },
    { title:'House in Brighton VIC', address:'19 South Rd, Brighton VIC 3186', suburb:'Brighton', state:'VIC', price:3200000, price_formatted:'$3,200,000', listing_type:'sale', beds:4, baths:3, parking:2, sqm:680, property_type:'House', year_built:2020, description:'Newly built luxury residence in the Brighton Golden Mile. Four bedrooms with ensuites, open-plan living with bi-fold doors to a heated pool and manicured garden. Stone kitchen with integrated Gaggenau appliances.', features:['Heated pool','Double garage','Ducted heating','Stone kitchen','Alarm','Landscaped garden'], slug:'house-brighton-vic-o5p6q7r8', img_i:2, days:10 },
    { title:'Edwardian in Hawthorn VIC', address:'42 Barkers Rd, Hawthorn VIC 3122', suburb:'Hawthorn', state:'VIC', price:2450000, price_formatted:'$2,450,000', listing_type:'sale', beds:4, baths:2, parking:2, sqm:520, property_type:'House', year_built:1910, description:'Stately Edwardian residence with original leadlight, tessellated tiles and mature elm-lined frontage. Spacious family room extends to a bluestone-paved alfresco. Close to Scotch College, Swinburne University and Glenferrie shops.', features:['Leadlight windows','Bluestone paving','Ducted heating','Double garage','Study nook','Established garden'], slug:'edwardian-hawthorn-vic-p6q7r8s9', img_i:3, days:13 },
    { title:'Apartment in Docklands VIC', address:'2103/80 Lorimer St, Docklands VIC 3008', suburb:'Docklands', state:'VIC', price:890000, price_formatted:'$890,000', listing_type:'sale', beds:2, baths:2, parking:1, sqm:82, property_type:'Apartment', year_built:2017, description:'High-floor Docklands apartment with sweeping views of the Yarra River and Bolte Bridge. Stone benchtops, soft-close cabinetry and floor-to-ceiling windows. Building offers pool, spa and residents\' cinema.', features:['River views','Pool','Spa','Cinema room','Storage cage','Video intercom'], slug:'apartment-docklands-vic-q7r8s9t0', img_i:4, days:16 },
    { title:'Bungalow in Kew VIC', address:'8 Studley Park Rd, Kew VIC 3101', suburb:'Kew', state:'VIC', price:2750000, price_formatted:'$2,750,000', listing_type:'sale', beds:4, baths:2, parking:2, sqm:650, property_type:'House', year_built:1920, description:'Gracious Californian bungalow on a tree-lined Kew boulevard with views to the Yarra parklands. Wide central hallway, bay windows and deep front verandah. North-facing rear garden with established camellias.', features:['Bay windows','Front verandah','Double garage','Ducted gas','Established garden','Walk to tram'], slug:'bungalow-kew-vic-r8s9t0u1', img_i:5, days:4 },
    { title:'Apartment in Melbourne CBD VIC', address:'18/350 La Trobe St, Melbourne VIC 3000', suburb:'Melbourne', state:'VIC', price:700, price_formatted:'$700/wk', listing_type:'rent', beds:2, baths:1, parking:1, sqm:70, property_type:'Apartment', year_built:2021, description:'Brand-new two-bedroom apartment in the heart of Melbourne\'s legal precinct. Integrated kitchen with Bosch appliances and engineered timber flooring. Building amenities include rooftop garden, gym and co-working space.', features:['Rooftop garden','Gym','Co-working space','Dishwasher','Air conditioning'], slug:'apartment-melbourne-cbd-vic-s9t0u1v2', img_i:6, days:2 },

    // ── Brisbane ──
    { title:'Queenslander in New Farm QLD', address:'34 Moray St, New Farm QLD 4005', suburb:'New Farm', state:'QLD', price:2100000, price_formatted:'$2,100,000', listing_type:'sale', beds:4, baths:2, parking:2, sqm:810, property_type:'House', year_built:1915, description:'Classic raised Queenslander on a generous 810 sqm block with city skyline glimpses. Wrap-around verandah, VJ walls and polished hardwood floors throughout. Separate studio beneath with potential for dual living.', features:['Wrap-around verandah','Studio','Polished hardwood','VJ walls','Solar panels','Dual living potential'], slug:'queenslander-new-farm-qld-t0u1v2w3', img_i:7, days:6 },
    { title:'Apartment in South Brisbane QLD', address:'506/25 Connor St, South Brisbane QLD 4101', suburb:'South Brisbane', state:'QLD', price:695000, price_formatted:'$695,000', listing_type:'sale', beds:2, baths:1, parking:1, sqm:75, property_type:'Apartment', year_built:2018, description:'Modern apartment in vibrant South Brisbane precinct overlooking the Brisbane River. Open-plan layout with stone kitchen and covered balcony. Walk to GOMA, South Bank Parklands and the city ferry.', features:['River views','Balcony','Pool','Gym','Intercom','Storage cage'], slug:'apartment-south-brisbane-qld-u1v2w3x4', img_i:8, days:19 },
    { title:'House in Ascot QLD', address:'12 Lancaster Rd, Ascot QLD 4007', suburb:'Ascot', state:'QLD', price:2950000, price_formatted:'$2,950,000', listing_type:'sale', beds:5, baths:4, parking:3, sqm:960, property_type:'House', year_built:2015, description:'Prestige family home in blue-chip Ascot with resort-style pool and outdoor kitchen. Five bedrooms with walk-in robes, home cinema and temperature-controlled wine room. Minutes to Eagle Farm racecourse and Portside Wharf.', features:['Resort pool','Home cinema','Wine room','Outdoor kitchen','Triple garage','Smart home','Solar'], slug:'house-ascot-qld-v2w3x4y5', img_i:9, days:3 },
    { title:'Townhouse in Paddington QLD', address:'5/28 Given Tce, Paddington QLD 4064', suburb:'Paddington', state:'QLD', price:980000, price_formatted:'$980,000', listing_type:'sale', beds:3, baths:2, parking:1, sqm:135, property_type:'Townhouse', year_built:2012, description:'Boutique townhouse on the doorstep of Paddington\'s antique row and Latrobe Terrace cafes. Three bedrooms over two levels with a private courtyard and rooftop deck. Air-conditioned throughout with polished timber stairs.', features:['Rooftop deck','Courtyard','Air conditioning','Polished timber','Built-in robes'], slug:'townhouse-paddington-qld-w3x4y5z6', img_i:10, days:17 },

    // ── Perth ──
    { title:'House in Cottesloe WA', address:'9 Marine Pde, Cottesloe WA 6011', suburb:'Cottesloe', state:'WA', price:3100000, price_formatted:'$3,100,000', listing_type:'sale', beds:4, baths:3, parking:2, sqm:720, property_type:'House', year_built:2016, description:'Striking contemporary residence just one street back from Cottesloe Beach. Infinity-edge pool, rooftop terrace and floor-to-ceiling glazing capture Indian Ocean sunsets. Chef\'s kitchen with Miele appliances and butler\'s pantry.', features:['Infinity pool','Rooftop terrace','Ocean views','Butler\'s pantry','Double garage','Ducted AC'], slug:'house-cottesloe-wa-x4y5z6a7', img_i:11, days:5 },
    { title:'Federation in Subiaco WA', address:'38 Hamersley Rd, Subiaco WA 6008', suburb:'Subiaco', state:'WA', price:1750000, price_formatted:'$1,750,000', listing_type:'sale', beds:4, baths:2, parking:2, sqm:510, property_type:'House', year_built:1905, description:'Lovingly restored Federation home with bullnose verandah, jarrah floors and ornate fretwork. Rear extension provides a contemporary family room and alfresco. Walk to Subiaco Oval precinct and Rokeby Road shops.', features:['Jarrah floors','Bullnose verandah','Alfresco','Ducted evaporative','Double carport','Bore reticulation'], slug:'federation-subiaco-wa-y5z6a7b8', img_i:0, days:20 },
    { title:'Apartment in Perth CBD WA', address:'1802/50 Murray St, Perth WA 6000', suburb:'Perth', state:'WA', price:720000, price_formatted:'$720,000', listing_type:'sale', beds:2, baths:1, parking:1, sqm:78, property_type:'Apartment', year_built:2020, description:'Sky-high apartment in Perth\'s newest luxury tower with 180-degree views of Kings Park and the Swan River. Stone kitchen, integrated Bosch appliances and floor-to-ceiling glass. Residents\' infinity pool, gym and lounge.', features:['Kings Park views','Infinity pool','Gym','Concierge','Storage','Video intercom'], slug:'apartment-perth-cbd-wa-z6a7b8c9', img_i:1, days:8 },
    { title:'House in Nedlands WA', address:'15 Bruce St, Nedlands WA 6009', suburb:'Nedlands', state:'WA', price:2400000, price_formatted:'$2,400,000', listing_type:'sale', beds:5, baths:3, parking:2, sqm:830, property_type:'House', year_built:1960, description:'Mid-century family home on an expansive Nedlands block with river glimpses. Five bedrooms, rumpus room and a sparkling below-ground pool surrounded by mature gardens. Minutes to UWA, Dalkeith shops and the river foreshore.', features:['Pool','River glimpses','Rumpus room','Double garage','Bore','Mature gardens'], slug:'house-nedlands-wa-a7b8c9d0', img_i:2, days:11 },

    // ── Adelaide ──
    { title:'Sandstone Villa in Norwood SA', address:'21 The Parade, Norwood SA 5067', suburb:'Norwood', state:'SA', price:1350000, price_formatted:'$1,350,000', listing_type:'sale', beds:4, baths:2, parking:2, sqm:450, property_type:'House', year_built:1895, description:'Elegant bluestone villa with return verandah, high ceilings and original fireplaces on the vibrant Norwood Parade. Rear extension with bi-fold doors to a landscaped garden. Zoned for Norwood Morialta High School.', features:['Bluestone facade','Return verandah','Fireplace','Ducted RC','Double carport','Landscaped garden'], slug:'villa-norwood-sa-b8c9d0e1', img_i:3, days:9 },
    { title:'Contemporary in Glenelg SA', address:'4 Colley Tce, Glenelg SA 5045', suburb:'Glenelg', state:'SA', price:1950000, price_formatted:'$1,950,000', listing_type:'sale', beds:4, baths:3, parking:2, sqm:380, property_type:'House', year_built:2022, description:'Brand-new contemporary home one block from Glenelg Beach with ocean views from the master suite. Seamless indoor-outdoor flow to a heated plunge pool and alfresco dining. Hydronic heating and 10 kW solar system.', features:['Ocean views','Plunge pool','Hydronic heating','Solar 10kW','Alfresco','Double garage'], slug:'contemporary-glenelg-sa-c9d0e1f2', img_i:4, days:7 },

    // ── Other ──
    { title:'House in Noosa Heads QLD', address:'8 Seaview Tce, Noosa Heads QLD 4567', suburb:'Noosa Heads', state:'QLD', price:3400000, price_formatted:'$3,400,000', listing_type:'sale', beds:4, baths:3, parking:2, sqm:650, property_type:'House', year_built:2019, description:'Luxury coastal retreat perched above Noosa Main Beach with panoramic ocean and hinterland views. Resort-style pool, outdoor shower and lush tropical landscaping. Minutes to Hastings Street boutiques and restaurants.', features:['Ocean views','Resort pool','Outdoor shower','Tropical garden','Double garage','Ducted AC'], slug:'house-noosa-heads-qld-d0e1f2g3', img_i:5, days:2 },
    { title:'Apartment in Broadbeach QLD', address:'2205/2 Oracle Blvd, Broadbeach QLD 4218', suburb:'Broadbeach', state:'QLD', price:1450000, price_formatted:'$1,450,000', listing_type:'sale', beds:3, baths:2, parking:2, sqm:130, property_type:'Apartment', year_built:2017, description:'Premium 22nd-floor apartment in iconic Oracle tower with sweeping Surfers Paradise skyline and ocean views. Three bedrooms with walk-in robes, stone kitchen and private plunge pool on balcony. Full resort facilities.', features:['Ocean views','Plunge pool','Resort facilities','Concierge','Triple car space','Wine storage'], slug:'apartment-broadbeach-qld-e1f2g3h4', img_i:6, days:14 },
    { title:'Heritage Home in Bowral NSW', address:'17 Bong Bong St, Bowral NSW 2576', suburb:'Bowral', state:'NSW', price:1280000, price_formatted:'$1,280,000', listing_type:'sale', beds:4, baths:2, parking:2, sqm:1200, property_type:'House', year_built:1910, description:'Charming Edwardian homestead on a generous Bowral block with established English-style gardens. Four bedrooms with original fireplaces, wraparound verandah and a detached studio. Walk to Bowral village and Corbett Gardens.', features:['English garden','Wraparound verandah','Fireplace','Studio','Double garage','1200sqm block'], slug:'heritage-bowral-nsw-f2g3h4i5', img_i:7, days:10 },
    { title:'House in Barton ACT', address:'24 National Cct, Barton ACT 2600', suburb:'Barton', state:'ACT', price:1680000, price_formatted:'$1,680,000', listing_type:'sale', beds:4, baths:3, parking:2, sqm:580, property_type:'House', year_built:2014, description:'Architecturally designed residence in Canberra\'s parliamentary triangle with Lake Burley Griffin views. Four bedrooms, home office and a north-facing entertainer\'s courtyard. Walk to Parliament House, Kingston foreshore and Manuka shops.', features:['Lake views','Home office','Courtyard','Double garage','Ducted heating','Solar panels'], slug:'house-barton-act-g3h4i5j6', img_i:8, days:6 },
  ];

  const rows = props.map((p) => ({
    agent_id: aid,
    title: p.title,
    address: p.address,
    suburb: p.suburb,
    state: p.state,
    country: 'Australia',
    price: p.price,
    price_formatted: p.price_formatted,
    listing_type: p.listing_type,
    beds: p.beds,
    baths: p.baths,
    parking: p.parking,
    sqm: p.sqm,
    property_type: p.property_type,
    description: p.description,
    features: p.features,
    image_url: img(p.img_i),
    images: [img(p.img_i)],
    slug: p.slug,
    is_active: true,
    views: v(),
    listed_date: recentDate(p.days),
    year_built: p.year_built,
  }));

  const { error } = await supabase.from('properties').insert(rows as any);
  if (error) throw error;
  return rows.length;
}
